spring:
  application: 
    name: EMS-INSTITUTE
  datasource:
    url: jdbc:mysql://localhost:3306/ems_institute
    username: root
    password: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
  profiles:
    active: dev 

server:  port: 4002

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:4340/eureka/          